### ISSUE TITLE
Content import issues

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-services#11]
-Tiles for Ghostsigns channel appear duplicates

-Tiles for London at war channel do not appear, and they were shown previously.

**Comment by wilsonpage** [comment]
Here's an example:
https://tengam.org/content/v1/search/beacons/51.5558711,-0.0481602,1500

The result shows 4 items, although the 'LondonAtWar' items are duplicates of the first 2 `GhostSigns` items.

**Comment by wilsonpage** [comment]
@isabelrios @oteo unrelated the two `GhostSigns` items are different, but actually about the same POI/story.

**Comment by isabelrios** [comment]
@wilsonpage @samgiles I have seen that there were different descriptions and pictures taken for the same POI, I am identifying the ones duplicated and will delete the rows in the corresponding tab Flickr_Ghostsigns of the content spreadsheet

**Comment by wilsonpage** [comment]
@isabelrios nice!

**Comment by isabelrios** [comment]
Not sure if that is clear :), reagarding Ghostsigns there are two issues:
-For every POI there are two tiles shown on the app
-For some POI the content is duplicated, I am identifying the rows duplicated to remove them. The description was different and slightly different also the location and the picture, but is the same POI. It would be needed to import the content again once I finish removing the rows.

**Comment by isabelrios** [comment]
Second issue mentioned in previous comment should be fixed now. I have updated the tab Flickr_Ghostsigns removing the rows that were referring to same POIs.
We would need to import this tab again @samgiles to avoid having the several tiles per POI.
Thanks!

**Comment by isabelrios** [comment]
This is fixed now.
Flickr Ghostsigns tiles are not duplicated
Flickr London at war tiles are shown
