### ISSUE TITLE
We need to add some POIs so Isabel and Maria can do some testing in Spain

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-services#14]
Until now we have been able to fake the GPS location with apps or with the Xcode simulator but it's not enough for testing the notifications as now the app willl notifiy when there is a change in the location.

@samgiles we need you to include these tests POIs, we can use the channel "Test" so later we can remove them easily:
For Maria: "test", 41.6389956, -0.8856567,  https://twitter.com/MariaOteo

**Comment by isabelrios** [comment]
For Isabel: "test", 40.502258, -3.704117, https://twitter.com/riosisabel
                  "test", 37.209195, -3.629823, https://github.com/isabelrios/

**Comment by oteo** [comment]
@djabberwocky @dbialer add your POIs if you want to give it a try, so Sam will be able to add them to the DB.
In the mean time I have added in the wiki some instructions to fake your location: https://wiki.mozilla.org/Faking_location_in_Android_and_iOS_to_discover_Virtual/GPS_locations

**Comment by samgiles** [comment]
@oteo @isabelrios I've added those points, I just use this tool:

https://github.com/mozilla-magnet/magnet-services/blob/master/content-service/bin/live-tool

If you clone the repository and run that with the apikey I sent in an email a week or so ago you should be good to add points.

**Comment by oteo** [comment]
we have already tested the POIs and tried the tool, it will be very helpful for us
Thanks a lot  @samgiles !
