### ISSUE TITLE
No POIs for London war Flickr group source

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-services#15]
I've not been able to discover POIs for this source... I am wondering if perhaps there was something wrong when injecting the content in the Data Base.

Tab in the spreadsheet: https://docs.google.com/spreadsheets/d/1RJe6D2CdDxYyp_vYC4cTMyXO8RwnfALgiKyM1H3BbdQ/edit#gid=580866279

@samgiles could you please have a look at it?

**Comment by isabelrios** [comment]
I had the same problem, mentioned in issue #11  (will not close it because it also covers the issue with Ghostsigns)

**Comment by oteo** [comment]
POIs are already included, and I can see the tile correctly in iOS and Android
