### ISSUE TITLE
Clarify channel_name or channel_id

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-services#22]
I've noticed we have the concept of a `channel_name` and `channel_id`. The 'get-all-channels' route returns both, but the 'search-for-beacons-here' route returns only `channel_name`. IMO we should move to an ID that never changes and inflate/join this model when required.

@samgiles what you recon?

**Comment by samgiles** [comment]
Yeh, I've made a PR to start to make this consistent.  #24

**Comment by samgiles** [comment]
This will consistently be `channel` as an indentifier.

**Comment by wilsonpage** [comment]
@samgiles could you patch magnet-client so we can land simultaneously?

**Comment by samgiles** [comment]
It'll be backwards compatible for older clients.  Will open a PR though once this has been deployed.

**Comment by samgiles** [comment]
`channel_id` everywhere.  The convention is to be:
A resource has an `id` field, and if it refers to another resource, it does so with a `<thing>_id` field.

Really these relationships should be hyperlinks... but, for simplicity's sake, we'll stick with this for now.
