### ISSUE TITLE
London History Group source is back and now UncoveredLondon down

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-services#23]
Unfortunately, after importing the POIs, the web page has changed again so we need to:

1. Remove the POIs that correspond to UncoveredLondon.
2. Include the POIs for LOndon History Group (the .csv file has been added in https://drive.google.com/open?id=0B01m7pXAhdJmVWtlNzc4TC0tZXM)

**Comment by samgiles** [comment]
Removed UncoveredLondon and added LondonHistoryGroup.
