### ISSUE TITLE
We need to reimport London History Group source

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-services#27]
Doing some testing I have realized that some of the POIs from this source were duplicated.

The problem was in the content extraction, we extracted the POIs from each period web page and, unfortunately, some POIs belongs to several periods.

I have cleaned the csv file and the new one "LondonHistoryGroup.csv" is already available in our Drive (https://drive.google.com/open?id=0B01m7pXAhdJmaldiR3BOblQzTzA)

@samgiles, the best is removing the source and injecting all the POIs again

**Comment by oteo** [comment]
Just for your info, the tiles are duplicated only in iOS, in Android it seems that the app is able to check that the there are several Virtual Beacons with the same URL and only one is shown.
@wilsonpage does the Android client this checking? I am not completely sure but I think that I saw this issue also in Android when I opened this bug

**Comment by samgiles** [comment]
@oteo I've re-imported this now.
