### ISSUE TITLE
Insert in the MetadataServer POIs for Atlas Obscura in SF and Hawaii and SF secrets

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-services#31]
POIs for Atlas Obscura in SF and SF secrets so Wilson can do some testing there

The csv files are in our Google Dive (Magnet/Public/Virtual Beacon Content/San Francisco/CSV files)
https://drive.google.com/open?id=0B01m7pXAhdJmYUpFUTBEcjh4aGs
Files: SFsecrets.csv and AtlasObscura.csv

POIs for Atlas Obscura in Hawaii
The csv file is included in Google Drive (Magnet/Public/Virtual Beacon Content/Hawaii/CSV fies) https://drive.google.com/open?id=0B01m7pXAhdJmRjZaeVcxTjRpY0U
Files: AtlasObscura.csv

**Comment by samgiles** [comment]
These are imported now.

**Comment by oteo** [comment]
Hi @samgiles

I am seeing the SF POIs from atlas Obscura and SF Secrets but I am not seeing the POIs for Atlas Obscura in Hawaii (although the channel is included in the Subscription screen)
Could you please check it? I am going to create another issue to track this in the meantime

**Comment by samgiles** [comment]
Ok, I've added them, I should've checked the response from the server when I uploaded - it had errored because the format of the CSV was a bit different and I didn't notice.  Should be fixed now.
