### ISSUE TITLE
Insert in the Metadata server the POIs for "A London Inheritance", "Street Art London" and "Jack the Ripper Tour" sources

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet-services#32]
The CSV files (ALondonInheritance.csv, StreetArtLondon.csv and JackTheRipperTour.csv) are ready to be injected in https://drive.google.com/open?id=0B01m7pXAhdJmVWtlNzc4TC0tZXM

**Comment by samgiles** [comment]
These have been imported.
